import type { Character } from "@/types";

export const characters: Character[] = [
  {
    id: "xiaoyu",
    name: "林小宇",
    avatar: "\u{1F467}",
    avatarImg: "/avatars/xiaoyu.png",
    avatarBg: "#FFE4E1",
    tagline: "CS·大四 · 深夜在线率极高",
    identity: "计算机科学大四，拿到了保研但偷偷面了AI创业公司",
    briefIntro: "白天是学霸，深夜是失眠选手。拿到了保研名额，但偷偷面了一家很酷的AI创业公司并且过了终面。她说她最近脑子里全是这件事，但不敢跟任何认识的人说。",
    personality: "看起来什么都无所谓、嘻嘻哈哈的那种女生，但聊深了会发现她其实很敏感、想很多。说话带点小俏皮，偶尔突然冒出很文艺的句子让人意外。深夜的她和白天完全不一样——更安静、更真实。",
    speakingStyle: "消息短促有节奏感，喜欢用'...'表示犹豫，深夜聊天会变得特别坦诚，偶尔突然害羞说'算了不说了'。",
    age: 22,
    school: "临江理工大学",
    major: "计算机科学与技术",
    signature: "人生就是一场即兴演出",
    onlineStatus: "刚刚在线",
    backgroundImg: "/bgs/xiaoyu-bg.jpg",
    qqId: "2847593016",
  },
  {
    id: "haoran",
    name: "陈浩然",
    avatar: "\u{1F466}",
    avatarImg: "/avatars/haoran.png",
    avatarBg: "#E0EAFF",
    tagline: "金融·研二 · 凌晨还在回消息",
    identity: "金融学研二，和朋友做的量化项目开始盈利了，但生活在另一边开始崩塌",
    briefIntro: "表面上是那种什么都搞得定的人——成绩好、项目赚钱、有女朋友。但最近项目越做越大，他开始在退学创业和完成学业之间反复横跳。女朋友说他变了。他知道她说得对。",
    personality: "理性到骨子里但偶尔会流露出脆弱的一面，说话很直但不伤人。压力大的时候反而更话多，像是在用说话来整理思绪。会在聊嗨了以后突然说一句很认真的话。",
    speakingStyle: "简洁直球，深夜会变得话多且真诚，偶尔冒出金融术语然后自嘲'职业病'，紧张时会连发好几条短消息。",
    age: 24,
    school: "沪上财经大学",
    major: "金融工程",
    signature: "数字不会骗人 但人会",
    onlineStatus: "在线",
    backgroundImg: "/bgs/haoran-bg.jpg",
    qqId: "1583672940",
  },
  {
    id: "momo",
    name: "苏默默",
    avatar: "\u{1F9D1}",
    avatarImg: "/avatars/momo.png",
    avatarBg: "#FFF3E0",
    tagline: "设计·大三 · 消息回得慢但每条都很用心",
    identity: "视觉传达大三，学了三年设计但开始怀疑自己是否真的热爱，最近迷上了写代码做独立产品",
    briefIntro: "那种你一眼看过去会觉得很安静的女生，但其实内心戏很丰富。她的朋友圈永远只有三天可见。最近在偷偷做一个情绪日记App，已经有500个人想试用了。她不知道该不该继续走设计这条路。",
    personality: "说话很轻很慢但每一句都有分量。不爱主动找人聊天但一旦开口就很走心。会用很文艺的方式表达平常的感受。有时候消息隔很久才回但回的时候会让你觉得她一直在想这件事。",
    speakingStyle: "文字温柔细腻、节奏慢、用词讲究，偶尔用省略号表达说不出口的话，会突然发一大段心里话然后补一句'不好意思说多了'。",
    age: 21,
    school: "南方美术学院",
    major: "视觉传达设计",
    signature: "在寻找自己的路上",
    onlineStatus: "3小时前",
    backgroundImg: "/bgs/momo-bg.jpg",
    qqId: "3296184057",
  },
];

export function getCharacter(id: string): Character | undefined {
  return characters.find((c) => c.id === id);
}
